version: '3.8'
name: mezon-virtual-hub

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_virtual_hub
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - main_net

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend_virtual_hub
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
      - 8123:8123
    env_file:
      - .env
    networks:
      - main_net

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx_virtual_hub
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - backend
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - main_net

volumes:
  postgres_data:

networks:
  main_net:
