version: '3.8'
name: mezon-virtual-hub-dev

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - main_net

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.debug
    container_name: backend
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    environment:
      PORT: 8123
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
    ports:
      - "8123:8123"
    networks:
      - main_net

volumes:
  postgres_data:

networks:
  main_net: